name: "test action"
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: call cache deps
        uses: ./../centralized_github_actions/.github/actions/cache_deps

